### ISSUE TITLE
example files missing

### ISSUE THREAD

**Issue by igordot** [infphilo/centrifuge#10]
In the manual, there is an example for building a reference:
```
$CENTRIFUGE_HOME/centrifuge-build --conversion-table $CENTRIFUGE_HOME/example/reference/gi_to_tid.dmp --taxonomy-tree $CENTRIFUGE_HOME/example/reference/nodes.dmp --name-table $CENTRIFUGE_HOME/example/reference/names.dmp $CENTRIFUGE_HOME/example/reference/test.fa test
```
However, the `example/reference` directory only contains `test.fa`, so the command fails because other files are missing.

**Comment by infphilo** [comment]
I just fixed so that the packages have all the necessary files in that directory.
