### ISSUE TITLE
NT Database - Centrifuge-build warnings

### ISSUE THREAD

**Issue by isardi** [infphilo/centrifuge#100]
Hello,
I am trying to build the NT Database using the instruction from the manual.  I am following the instructions exactly as in the manual:

1) centrifuge-download -o taxonomy taxonomy
2) wget ftp://ftp.ncbi.nih.gov/blast/db/FASTA/nt.gz
3) gunzip nt.gz && mv -v nt nt.fa
4) wget ftp://ftp.ncbi.nih.gov/pub/taxonomy/gi_taxid_nucl.dmp.gz
5) gunzip -c gi_taxid_nucl.dmp.gz | sed 's/^/gi|/' > gi_taxid_nucl.map

Then to build the index I run:

centrifuge-build -p 16 --bmax 1342177280 --conversion-table gi_taxid_nucl.map --taxonomy-tree taxonomy/nodes.dmp --name-table taxonomy/names.dmp nt.fa nt

I am getting multiple warnings running centrifuge-build including:

Warning: Encountered reference sequence with only gaps

Warning: taxomony id doesn't exists for X17276.1! 
For this last warning a get a lot of them.  Not sure what I am missing.  Any help would be greatly appreciated.

Thanks!

**Comment by mourisl** [comment]
You also need to use download the accession number to taxonomy id conversion files. 
We have a script in the folder "indices" and you can use command "make THREADS=16 nt" to build indices or look for the downloading sites.
You probably will still get those warnings, which is normal.

**Comment by isardi** [comment]
Thanks!
