### ISSUE TITLE
Control bowtie-build

### ISSUE THREAD

**Issue by MeHelmy** [infphilo/centrifuge#104]
Hi,

It is written that:

> * bowtie-build main function.  It is placed in a separate source file
>  * to make it slightly easier to compile as a library.
>  *
>  * If the user specifies -A <file> as the first two arguments, main
>  * will interpret that file as having one set of command-line arguments
>  * per line, and will dispatch each batch of arguments one at a time to
>  * bowtie-build.

Is there any example how can I use `-A `option and example for the input parameter <file>.

Thanks,
Medhat

**Comment by mourisl** [comment]
This is to build several independent index. You need to use -A option by calling centrifuge-build-bin. 
The input parameter for -A is a file, where in this file, each line is a set of parameters used for centrifuge-build.
For example, the file can be like:
```
--name-table centrifuge_name.out --conversion-table centrifuge_conversion.out --taxonomy-tree centrifuge_tax.out centrifuge_ref.fa test`
--name-table centrifuge_name.out --conversion-table centrifuge_conversion.out --taxonomy-tree centrifuge_tax.out centrifuge_ref.fa test2
```

And after calling "centrifuge-build-bin -A file_name" you will get two indices test.\*.cf and test2.\*.cf

**Comment by MeHelmy** [comment]
Thanks a lot for the answer.
