### ISSUE TITLE
min-totallen default value 50 not 0

### ISSUE THREAD

**Issue by MeHelmy** [infphilo/centrifuge#105]
Hi,
In documentation: 

`--min-totallen <int>  minimum summed length of partial hits per read (default 0)`

But I think it should be :
`--min-totallen <int>  minimum summed length of partial hits per read (default 50)`

Thanks

**Comment by mourisl** [comment]
Thanks for pointing out this error.

The option min-totallen is not used Centrifuge because it can be easily done by going through the classification output. I just removed the option from the usage information.
