### ISSUE TITLE
centrifuge_report.csv is not csv

### ISSUE THREAD

**Issue by igordot** [infphilo/centrifuge#11]
The `centrifuge_report.csv` file is not a comma-separated file.

**Comment by infphilo** [comment]
I don't know whether or not this is an issue.  As far as I know, CSV also means a tab-separated file.

**Comment by igordot** [comment]
I agree this is not a real issue, but C stands for comma. There is even a Wikipedia page about it: https://en.wikipedia.org/wiki/Delimiter-separated_values

**Comment by infphilo** [comment]
Okay, I just changed csv to tsv, and released a new version.
