### ISSUE TITLE
Argument list too long...

### ISSUE THREAD

**Issue by shlomobl** [infphilo/centrifuge#116]
Hi,

I used Centrifuge with viral genomes and it worked very nice!

Now I wish to add bacterial genomes. I downloaded the whole thing including all levels of assembly, getting to 113,609 genomes total. Then I get the following error when trying the cat command. 

_bash: /usr/local/bin/centrifuge-build: Argument list too long_

I tried to direct the centrifuge-build command to library/bacteria/*.fna instead of giving it a 'cat' file, but got the same error. Any ideas on how to deal with this? Simply dividing the bacteria library in sub-directories?

Also, what genomes are included in the pre-built indexes, completed only or all assemblies? And once I download it, how to proceed, please?

Thanks!

**Comment by mourisl** [comment]
This is an issue related to bash when there are too many files. You can use xargs to get around this issue, for example: https://sites.google.com/site/tfsidc/linux-tricks/processing-a-large-number-of-files.

**Comment by shlomobl** [comment]
Thanks for the hint but xargs did not work:

_/centrifuge/library/bacteria$ ls *.fna | xargs -n 32 -P 8 cat >> ../../input-sequences-bacteria.fna
bash: /bin/ls: Argument list too long_

With any combination of -n and -P :-\

**Comment by mourisl** [comment]
Because that is a long argument list for "ls *.fna". I would suggest to use 
ls | grep ".fna$" |  xargs -n 32 -P 8 cat >> ...
