### ISSUE TITLE
multiple index files

### ISSUE THREAD

**Issue by shlomobl** [infphilo/centrifuge#118]
Hi,

Is it possible to run centrifuge with multiple index files (*.cf)?

Say I want to build .cf files separately for viral, bacteria etc. genomes and chose what to look for each time.

**Comment by mourisl** [comment]
No, Centrifuge does not support this feature.
You can run centrifuge separately, and merge the classiciation result by pick the highest score.

**Comment by KristinaGagalova** [comment]
Hi, 
I have a quation about that. Does the score depend on the index size as well? Are the scores directly comparable between indexes?
