### ISSUE TITLE
Stuck on opening index

### ISSUE THREAD

**Issue by briansaint** [infphilo/centrifuge#119]
Hello,

I am trying to run the centrifuge on a linux system.
However when i go to run the test data it seems to get stuck on opening the index. 
Right now i have 48gb RAM and 24 CPUs on this linux machine. 
On my mac, i can run this in two seconds.
So i know this shouldn't be taking this long. 
Any idea why this is happening?

-Brian 

***

[brian@adam example]$ perl ../centrifuge -x index/test -f reads/input.fa -S out --verbose  --report-file out_two -p 16
(INFO): Before arg handling:
(INFO):   Wrapper args:
[  ]
(INFO):   Binary args:
[ -x index/test -f reads/input.fa -S out --verbose --report-file out_two -p 16 ]
(INFO): After arg handling:
(INFO):   Binary args:
[ -x index/test -f reads/input.fa -S out --verbose --report-file out_two -p 16 ]
(INFO): /home/brian/centrifuge-1.0.3-beta/example/../centrifuge-class --wrapper basic-0 -x index/test -f reads/input.fa -S out --verbose --report-file out_two -p 16
Applying preset: 'sensitive' using preset menu 'V0'
Final policy string: 'SEED=0,22;DPS=15;ROUNDS=2;IVAL=S,1,1.15'
Input bt2 file: "index/test"
Query inputs (DNA, FASTA):
  reads/input.fa
Quality inputs:
Output file: "out"
Local endianness: little
Sanity checking: disabled
Assertions: disabled
Entered driver(): 14:41:22
Creating PatternSource: 14:41:22
Opening hit output file: 14:41:22
About to initialize fw Ebwt: 14:41:22
Trying index/test
  About to open input files: 14:41:22
Opening "index/test.1.cf"
Opening "index/test.2.cf"
  Finished opening input files: 14:41:22
  Reading header: 14:41:22
Headers:
    len: 1073
    bwtLen: 1074
    sz: 269
    bwtSz: 269
    lineRate: 7
    offRate: 4
    offMask: 0xfffffffffffffff0
    ftabChars: 10
    eftabLen: 20
    eftabSz: 160
    ftabLen: 1048577
    ftabSz: 8388616
    offsLen: 68
    offsSz: 544
    lineSz: 128
    sideSz: 128
    sideBwtSz: 96
    sideBwtLen: 384
    numSides: 3
    numLines: 3
    ebwtTotLen: 384
    ebwtTotSz: 384
    color: 0
    reverse: 0
Reading plen (2): 14:41:22
Opening "index/test.3.cf"

**Comment by mourisl** [comment]
It seems the index in the example is out-dated. I've updated it and it should work now.

**Comment by briansaint** [comment]
Hey Li,

It still is getting stuck. 
Where did you put the update?
I downloaded from here https://github.com/infphilo/centrifuge/releases <https://github.com/infphilo/centrifuge/releases>. 

Also, when I go to do “make” I get the following.
Do you know what can be causing this warning?

-Brian 

**** 
****
****
****
[brian@aiden-brlin centrifuge-1.0.3]$ make
/usr/bin/g++  -O3 -m64 -msse2 -funroll-loops -g3 -DCOMPILER_OPTIONS="\"-O3 -m64 -msse2 -funroll-loops -g3 -DPOPCNT_CAPABILITY\"" -DPOPCNT_CAPABILITY \
-fno-strict-aliasing -DCENTRIFUGE_VERSION="\"1.0.3-beta\"" -DBUILD_HOST="\"`hostname`\"" -DBUILD_TIME="\"`date`\"" -DCOMPILER_VERSION="\"`/usr/bin/g++  -v 2>&1 | tail -1`\"" -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D_GNU_SOURCE   -DBOWTIE_MM  -DCENTRIFUGE -DBOWTIE2 -DBOWTIE_64BIT_INDEX -DNDEBUG -Wall \
 -I third_party \
-o centrifuge-build-bin centrifuge_build.cpp \
ccnt_lut.cpp ref_read.cpp alphabet.cpp shmem.cpp edit.cpp bt2_idx.cpp reference.cpp ds.cpp limit.cpp random_source.cpp tinythread.cpp diff_sample.cpp centrifuge_build_main.cpp \
-lpthread 
/usr/bin/g++  -O3 -m64 -msse2 -funroll-loops -g3 -DCOMPILER_OPTIONS="\"-O3 -m64 -msse2 -funroll-loops -g3 -DPOPCNT_CAPABILITY\"" -DPOPCNT_CAPABILITY \
-fno-strict-aliasing -DCENTRIFUGE_VERSION="\"1.0.3-beta\"" -DBUILD_HOST="\"`hostname`\"" -DBUILD_TIME="\"`date`\"" -DCOMPILER_VERSION="\"`/usr/bin/g++  -v 2>&1 | tail -1`\"" -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D_GNU_SOURCE   -DBOWTIE_MM   -DCENTRIFUGE -DBOWTIE2 -DBOWTIE_64BIT_INDEX -DNDEBUG -Wall \
 -I third_party  \
-o centrifuge-class centrifuge.cpp \
ccnt_lut.cpp ref_read.cpp alphabet.cpp shmem.cpp edit.cpp bt2_idx.cpp reference.cpp ds.cpp limit.cpp random_source.cpp tinythread.cpp qual.cpp pat.cpp read_qseq.cpp ref_coord.cpp mask.cpp pe.cpp aligner_seed_policy.cpp scoring.cpp presets.cpp simple_func.cpp random_util.cpp outq.cpp centrifuge_main.cpp \
-lpthread  
In file included from centrifuge.cpp:47:0:
classifier.h: In instantiation of ‘void Classifier<index_t, local_index_t>::searchForwardAndReverse(index_t, const Ebwt<index_t>&, const Scoring&, RandomSource&, const ReportingParams&, index_t) [with index_t = long unsigned int; local_index_t = short unsigned int]’:
classifier.h:238:72:   required from ‘int Classifier<index_t, local_index_t>::go(const Scoring&, const Ebwt<index_t>&, const Ebwt<index_t>&, const BitPairReference&, WalkMetrics&, PerReadMetrics&, HIMetrics&, SpeciesMetrics&, RandomSource&, AlnSinkWrap<index_t>&) [with index_t = long unsigned int; local_index_t = short unsigned int]’
centrifuge.cpp:2660:94:   required from here
classifier.h:647:16: warning: variable ‘cur’ set but not used [-Wunused-but-set-variable]
         size_t cur[2] = {0, 0} ;
                ^
/usr/bin/g++  -O3 -m64 -msse2 -funroll-loops -g3 \
-DCOMPILER_OPTIONS="\"-O3 -m64 -msse2 -funroll-loops -g3 -DPOPCNT_CAPABILITY\"" -DPOPCNT_CAPABILITY \
-fno-strict-aliasing -DCENTRIFUGE_VERSION="\"1.0.3-beta\"" -DBUILD_HOST="\"`hostname`\"" -DBUILD_TIME="\"`date`\"" -DCOMPILER_VERSION="\"`/usr/bin/g++  -v 2>&1 | tail -1`\"" -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D_GNU_SOURCE   -DBOWTIE_MM  -DCENTRIFUGE -DBOWTIE2 -DBOWTIE_64BIT_INDEX -Wall \
 -I third_party -I . \
-o centrifuge-inspect-bin centrifuge_inspect.cpp \
ccnt_lut.cpp ref_read.cpp alphabet.cpp shmem.cpp edit.cpp bt2_idx.cpp reference.cpp ds.cpp limit.cpp random_source.cpp tinythread.cpp \
-lpthread

**Comment by mourisl** [comment]
We haven't put that into the release yet. You can use git clone to get the package. Or you can just directly download the test.3.cf file from GitHub. There is no need to recompile centrifuge.

**Comment by briansaint** [comment]
Do you know how much ram would be needed to run the nt database?
I see in the paper that it says around 69Gb but that’s with BWA.

**Comment by mourisl** [comment]
I think now it takes about 120G memory to run nt database.
