### ISSUE TITLE
[Feature request] Add seq to "tab" outfmt

### ISSUE THREAD

**Issue by yeli7068** [infphilo/centrifuge#120]
Hi,
Could you add "seq" options to the tab output format as you did in sam output format?
This is really helpful for downstream analysis, e.g. assembly. I know it is not hard to do this but it is really time-consuming to add sequence to each reads especially when the inputs are from metagenmics ( >GBs in fastq).
If you think this is not a good idea, could you give me some tips how to add this function by myself through source codes?
Any helps from you will be highly appreciated.

**Comment by mourisl** [comment]
You can specify the option "--tab-fmt-cols" as readID,seqID,taxID,score,2ndBestScore,hitLength,queryLength,numMatches,readSeq,readQual
For mate pairs, the sequence are joined by the symbol "_".
