### ISSUE TITLE
Index building got stuck with more than 20 million RefSeq sequences

### ISSUE THREAD

**Issue by sooms1** [infphilo/centrifuge#122]
Dear colleague,

We are building centrifuge indexes for the complete RefSeq database. (1.6TB reserved for this job)

The building starts of as it always does, but after a while nothing seems to happen anymore. The log file of the job can be found here:
https://barmsijs.lumc.nl/sooms1/centrifuge.o8962018

When I ran the same job again with only the error output (-q option) I found this warning:
"Could not allocate space for a joined string of 1128068418933 elements.
Switching to a packed string representation."

Command I used:

centrifuge-build --bmax 1000000000 --dcv 2048 -p 16 --conversion-table mapfile_RefSeq_release/refseq.map --taxonomy-tree taxonomy/nodes.dmp --name-table taxonomy/names.dmp library_RefSeq_release/new_RefSeq_release.fa RefSeq_${versie}/RefSeq_${versie}_

The new_RefSeq_release.fa file is about 1.2TB uncompressed. It has more than 26 million sequences downloaded from Refseq. Maybe this hits the limit of centrifuge indexing script?

For your information, the .fai file of this fasta file can be downloaded here: https://barmsijs.lumc.nl/sooms1/new_RefSeq_release.fa.fai.gz

Among these >26 millions sequences, majority are NZ_, NW_.

Here are the counts of each prefix code:

cut -f1 -d"_" new_RefSeq_release.fa.fai |sort|uniq -c
     76 AC
  31388 NC
  40600 NG
   7456 NR
  35776 NT
14921644 NW
11760021 NZ

Although these NZ_, NW_ sequences belong to unfinished reference assemblies, they are still valuable for classification I think. But the huge number of them may pose problem for indexing? We would appreciate your suggestions/input on how to deal with this large list of reference sequences more efficiently.

Thanks a lot and we look forward to your feedbacks!

**Comment by hailiangmei** [comment]
Hi guys,

We would really appreciate some input on this question. Centrifuge offers pre-built index even with entire NT DB. So I don't think our list of reference sequences are too "large" to handle. Maybe we are missing some tricks to deal with inputs properly?

Thanks!

Leon

**Comment by hailiangmei** [comment]
@mourisl , thanks for your input! We have access to a 3TB machine, will try to reduce the number of sequences then.

So this sort of 4:1.2 memory consumption ratio can't be further reduced by trading off with CPU time?

**Comment by mourisl** [comment]
The --bmax which you already used can alleviate the issue. I'm not sure whether 3TB would work, but 1.6TB seems to close to the length of sequences and there are some data structures that can't be processed by splitting.
