### ISSUE TITLE
changing the default threshold of five labels per sequence

### ISSUE THREAD

**Issue by mghanbari** [infphilo/centrifuge#125]
Hi
According to t the Centrifuge paper _"The user can easily change the default threshold of five labels per sequence; for example, if this threshold is set to one, then Centrifuge will report only the lowest common ancestor as the taxonomic label, mimicking the behavior of Kraken."_However I could not find this option when I run centrifuge -h in Linux. Does anyone have an idea about this?
Regards
mahdi

**Comment by khyox** [comment]
Hi,
The flag is `-k`, so for mimicking the behavior of LMAT or Kraken and report just the LCA, it's `-k 1`.
Hope this helps!

**Comment by mourisl** [comment]
Thank you! I just added -k option to the help message.
