### ISSUE TITLE
using --police parameter

### ISSUE THREAD

**Issue by MeHelmy** [infphilo/centrifuge#126]
Hi,
I'm Using centrifuge with Oxford nanopore sequence, I am passing this parameter (to change gap penality seed length and match penality):

`centrifuge-class -x ./database/centrifuge/nt -U ./myseq.fastq -q -S ./test/classification.txt --report-file  ./test/classification.tsv -p 32 --min-hitlen 32 --verbose --policy  'MA=1;SEEDLEN=14;RDG=1,1' --mp 1,1 
`

But I do not see that this parameters were passed correctly 
` --policy  'MA=1;SEEDLEN=14;RDG=1,1' --mp 1,1 `

Is this way using `--policy` is wrong?  what is the right way to give this argument parameters?

Thanks.

**Comment by mourisl** [comment]
Centrifuge does not do the actual alignment, so the parameters --policy and --mp are not used.

**Comment by MeHelmy** [comment]
So how to change the alignment parameters?

**Comment by mourisl** [comment]
--mp is not defined in centrifuge, so you will get the error no matter what. And to make --policy parsing, you need to add "\" before ";" symbol. 

Since Centrifuge does not do alignment, I don't quite understand what do you mean by changing the alignment parameters.
