### ISSUE TITLE
bioconda recipe integration test fails

### ISSUE THREAD

**Issue by Krischan** [infphilo/centrifuge#127]
An attempt to update the centrifuge bioconda recipe [failed](https://circleci.com/gh/bioconda/bioconda-recipes/12305?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link), which seems to be related to #108 / #115. Should be fixed by commit 48022c471b90e39d6e85bbea2dafd3c8e033f327. Would be great if we could get an updated release.

**Comment by mourisl** [comment]
We re-release v1.0.4-beta with updated Makefile. Can you try it again?

**Comment by Krischan** [comment]
Thank you for the update. All [checks](https://github.com/bioconda/bioconda-recipes/pull/9243) have passed now.
