### ISSUE TITLE
Problem with centrifuge-download for too many taxIDs

### ISSUE THREAD

**Issue by danicic7** [infphilo/centrifuge#130]
Hi,

I've encountered a problem while using Centrifuge 1.0.3 when downloading reference sequences for a specific set of viral taxIDs. 
The command line looks like this:
centrifuge-download -o download -t 1589752,1589755,1542912,... -P 8 -d "viral" refseq > seqid2taxid.map; cat download/*/*.fna > input-sequences.fna 

(the argument -t contains ~300 comma separated taxIDs)

and it gives the following error:
/usr/local/bin/centrifuge-download: line 288:    16 Segmentation fault      (core dumped) awk -F "\t" "BEGIN {OFS=\"\t\"} $AWK_QUERY" "$FULL_ASSEMBLY_SUMMARY_FILE" > "$ASSEMBLY_SUMMARY_FILE"

However, when taking into consideration only 263 taxIDs, centrifuge-download works just fine, the problem arises when the number of taxIDs is greater than 263.

I don't see any issues reporting such a problem, nor it is pointed out in the Centrifuge Manual, so I wondered if there is any limitation in the number of taxIDs someone can list when downloading specific reference sequences?

Regards,
Aleksandar Danicic

**Comment by danicic7** [comment]
Just an update, I tried the same thing with Centrifuge v1.0.4-beta, and I got the same error.

**Comment by mourisl** [comment]
Could you please provide the full list of these 300 tax ids? I tried 400 tax ids it seems work fine on our server.
One way to resolve this is to download the genomes in batches and concatenate the seqid2taxid.map file.
There is also a typo in your command, "cat download//.fna" probably should be "cat download/*.fna"

**Comment by danicic7** [comment]
Yes, sorry, the typo was made when I copied the line here, it was not in the command line i tried.
Here is the complete command line:

centrifuge-download -o download -P 8 -t 437329,421012,10255,2170100,1569056,270161,1763507,11307,256994,2015376,663557,1343494,1634486,1540097,663560,1985698,1589265,1589270,1097753,1589274,319522,475178,1589297,12730,1187894,1351740,1056830,1056831,1056833,1114179,942165,114777,64186,1654883,1654884,1785960,1654889,1654891,1923483,1079999,442493,57477,1654919,934027,1235650,1654926,1654927,1654928,573591,1450142,1147042,1147043,1147044,1235654,1237159,434346,1161927,1720493,1622190,10693,1622192,1622193,1720498,1720500,1815957,1450169,1235659,1147094,1163482,1655012,1655014,1655015,1655016,557289,1655018,1655019,1655020,1655021,1655022,1655023,929832,929833,1007869,1147137,1147140,1147142,46242,1147144,1147145,1147146,1147147,1147148,11086,1147150,1147151,1147152,1147153,1147154,1147155,1147156,1147157,1147158,180504,925983,925984,925986,207597,1204516,1204517,1204521,90410,1204523,1204524,1204525,1204528,1204529,1204531,1204533,1204534,1204535,1204537,1204538,1204539,1204540,1204543,270673,926067,1237364,754037,754038,754039,754040,754041,754042,754043,754044,754045,754046,1417599,754048,754049,754051,754052,754053,754055,754056,1567468,754058,754059,1133293,754067,11085,754072,754073,754074,754075,1982901,1728958,1815969,1401297,1815972,279006,1589733,1458669,1458670,1589746,1589747,1589748,1589749,1589751,1589752,1589755,1542912,508419,644524,1678082,1597966,1278479,1458706,1458710,1458711,1597976,467481,1458714,1458715,1458716,1458717,1352227,1458724,1458725,1352230,549445,549446,293644,1573458,1090133,1090134,1141519,139870,139871,139872,1548901,1548902,1073767,369257,1548906,1548907,1837842,1548917,1245814,320122,172667,1654890,1526550,418443,1327758,1327759,11269,1327762,1327764,1327765,1327766,1458841,1327770,1327771,1327772,1327773,1327774,1327776,1327777,1458851,1458852,1458855,1458856,1458857,1458859,1458860,1458861,1458862,1458863,287412,1647285,1647286,877240,1245890,1049283,1647300,1647301,1647302,1647304,582345,1647306,1647308,1647309,1493508,1434319,1647313,384360,1572754,1690684,187764,1891703,1662330,1662332,1105286,1506716,348058,540067,540068,1777063,1777064,1777065,581037,420255 -d "viral" refseq

**Comment by mourisl** [comment]
This also works fine on our server. I think this might be some buffer size limit of awk on your system.

**Comment by danicic7** [comment]
Thank you a lot for the suggestion. Indeed, the problem was the size limit of awk, which was simply solved by installing gawk.
Now everything runs smoothly.
Thanks again for the quick response.
