### ISSUE TITLE
Feature request: output of genomic location in the classification

### ISSUE THREAD

**Issue by omixer** [infphilo/centrifuge#140]
Hello,

I was wondering if you could add an option to include the genomic location of each hit in the classification output? This way it would be rather straightforward to derive gene abundance without having to map the reads again! It could also help creating one profile with both taxonomic and functional annotation instead of two different matrices, which could be very helpful for downstream analysis!

Thanks,
Youssef

**Comment by mourisl** [comment]
Centrifuge does not do actual alignments, so we do not have any genomic location information. 
We are working on a way to provide extreme rough genomic location, which will be off by millions of bps, so that probably would not help with functional annotation either.

**Comment by omixer** [comment]
Indeed that would not be helpful. 
Thank you for the clarification and your swift reply!
