### ISSUE TITLE
centrifuge-build hangs silently on FASTA file with small sequences

### ISSUE THREAD

**Issue by dshivak** [infphilo/centrifuge#146]
Attached file fails to build and `centrifuge-build` hangs silently until killed.

FASTA line length wrapping does not change anything, removing one character from the 3' end of A_TP53_segment allows build to succeed.  Haven't tried changing kmer length to see if it's a boundary issue.

[centrifuge_build_testcase.zip](https://github.com/infphilo/centrifuge/files/2333203/centrifuge_build_testcase.zip)

**Comment by mourisl** [comment]
Thanks for sharing the data causing this bug. I have updated the code on GitHub so it should work now.
