### ISSUE TITLE
Extract specific kmer

### ISSUE THREAD

**Issue by novitch** [infphilo/centrifuge#151]
Hi, 
I am wondering if there is a way to extract the kmer signature of a certain gnome that I want to target.

I wasn't able to find a solution using centrifuge-inspect .

Thanks,

**Comment by mourisl** [comment]
What's the definition of kmer signature here?

**Comment by mourisl** [comment]
Oh, this is the genome compression stage, which is independent of index building. So such information is not kept in the index. 
Note that during the compression, the uniqueness means the portion is unique up so far. So it is possible that genome 3 has that 53-mer as well.

**Comment by mourisl** [comment]
If you used the compressed genome, there is no characteristic of genome 2 stored in the index. 
You can use the index for uncompressed genome and use centrifuge-inspect to find the sequence of genome 2.

**Comment by novitch** [comment]
Ok, I get it, sorry I miss understood how centrifuge building and index was working since a long time, so it took a long moment to change my mind.. 

Cheers,
