### ISSUE TITLE
Merged pair reads question

### ISSUE THREAD

**Issue by LeonardosMageiros** [infphilo/centrifuge#153]
Hi, 

I have many pair end reads fastq files from different metagenomic samples and I would like to pool them together so I can see the overall taxonomic profiling of my dataset. 

Is it conceptually ok if I just concatenate all the fastq files and then run centrifuge on this one big file? 
Am I loosing anything by merging pair reads in one file? 

Thank you very much for your help
Leonardos

**Comment by mourisl** [comment]
I would suggest you to concatenate the first mates in one file and the other mates in another file. The mate pair information should still be consistent in these two files.  
You will lose some information if two mates are not in the same line and not processed together.

**Comment by LeonardosMageiros** [comment]
I ll try that. Thank you very much.
