### ISSUE TITLE
--sample-sheet file

### ISSUE THREAD

**Issue by juulluu21** [infphilo/centrifuge#154]
Hi, 

Can I have an example of **--sample-sheet** file for paired end reads?

Thanks.

**Comment by mourisl** [comment]
Each line corresponds to one sample. And more paired-end reads samples, it can be like:
2	sample_1_r1.fq	sample_1_r2.fq	sample_1.classification	sample_1.report
2	sample_2_r1.fq	sample_2_r2.fq	sample_2.classification	sample_2.report
2	sample_3_r1.fq	sample_3_r2.fq	sample_3.classification	sample_3.report
...

**Comment by juulluu21** [comment]
Oh! Thank you!!
