### ISSUE TITLE
16S rRNA database

### ISSUE THREAD

**Issue by mbhall88** [infphilo/centrifuge#159]
Not so much an issue as a question.   
Have you or anyone you know created a centrifuge database for 16S rRNA (i.e with [Silva](https://www.arb-silva.de/) or [NCBI's RefSeq Target Loci](https://www.ncbi.nlm.nih.gov/bioproject?db=bioproject&Cmd=DetailsSearch&Term=33175%5Buid%5D))?  

I know I can make my own but thought this seems standard enough that someone may have done this already?

**Comment by mbhall88** [comment]
@gabyrech Not yet. But I will update if I do.

**Comment by mourisl** [comment]
Have you tried the most recent version of Centrifuge by "git pull"? There was a bug fixing that Centrifuge would stuck on short sequence when building index.

**Comment by mbhall88** [comment]
I'm using the more recent release (Centrifuge v1.0.4-beta). I'll give the latest commit a try.

**Comment by mourisl** [comment]
Can you show me some headers of the sequences in your reference fasta? 
The '0' may mean Centrifuge could not parse the taxonomy id from the headers.

**Comment by mbhall88** [comment]
```
>GY203941.1.1493 Bacteria;Bacteroidetes;Bacteroidia;Bacteroidales;Prevotellaceae;Prevotella 7;unidentified
>GY324971.1.1500 Bacteria;Proteobacteria;Gammaproteobacteria;Vibrionales;Vibrionaceae;Photobacterium;unidentified
>JQ765433.1.1505 Bacteria;Firmicutes;Bacilli;Bacillales;Bacillaceae;Bacillus;Bacillus vallismortis
>JQ765578.1.1444 Bacteria;Proteobacteria;Gammaproteobacteria;Betaproteobacteriales;Burkholderiaceae;Burkholderia-Caballeronia-Paraburkholderia;Burkholderia sp. BRHS/P92
>JQ766308.1.1248 Bacteria;Tenericutes;Mollicutes;Mollicutes Incertae Sedis;Unknown Family;Candidatus Phytoplasma;Cabbage stunt phytoplasma
>JQ768370.1.1499 Bacteria;Proteobacteria;Gammaproteobacteria;Pseudomonadales;Pseudomonadaceae;Pseudomonas;Pseudomonas otitidis
>JQ770191.1.1372 Bacteria;Firmicutes;Bacilli;Lactobacillales;Enterococcaceae;Vagococcus;Vagococcus sp. SVI4
>JQ771130.1.1499 Bacteria;Proteobacteria;Gammaproteobacteria;Pseudomonadales;Moraxellaceae;Acinetobacter;Acinetobacter nectaris
>JQ771139.1.1497 Bacteria;Proteobacteria;Gammaproteobacteria;Pseudomonadales;Moraxellaceae;Acinetobacter;Acinetobacter boissieri
>JQ771208.1.1265 Bacteria;Proteobacteria;Gammaproteobacteria;Betaproteobacteriales;Burkholderiaceae;Burkholderia-Caballeronia-Paraburkholderia;Burkholderia sp. UFLA04-312
```

**Comment by mourisl** [comment]
I guess those sequence ids ("GY203941.1.1493") is not in the seqid_to_taxid.map or *.map file.  It seems one can obtain the taxonomy id through the species name (taxonomy/names.dmp) from in those headers and can append those information to the *.map file. 
I don't know whether such information is already online or not.

**Comment by mbhall88** [comment]
Hi @mourisl . Thanks again for helping out.  

All of those sequence IDs are in my `seqid2taxid.map` file with their corresponding tax ID...

**Comment by mourisl** [comment]
From another issue, it seems that seqid2taxid.map in Kraken is a bit different from Centrifuge uses.
The seqid2taxid.map in Centrifuge would look like "GY203941.1.1493\t[tax_ID]" a tab-delimited file. Is the format same? Thanks.

**Comment by mbhall88** [comment]
Yes the format is the same. See an example from the kraken2 `seqid2taxid.map` file

```
A16379.1.1485   3698
A45315.1.1521   25620
A58083.1.1474   449
A61579.1.1437   26952
A97104.7.1522   1853
AAAA02010377.14668.16277        2805
AAAA02020706.141.1662   3523
```

**Comment by mourisl** [comment]
Could you please show me the entries for GY203941.1.1493 in the nodes.dmp and names.dmp file based on the taxonomy id found in the seqid2taxid.map file? Thanks.

**Comment by mourisl** [comment]
I just noticed that the command you use for centrifuge-build is wrong. It should be
KRAKEN2_DB_DIR=kraken2_16s_db/
centrifuge-build \
   --threads 32 \
   --conversion-table "$KRAKEN2_DB_DIR"/seqid2taxid.map \
   --taxonomy-tree "$KRAKEN2_DB_DIR"/taxonomy/nodes.dmp \
   --name-table "$KRAKEN2_DB_DIR"/taxonomy/names.dmp \
    "$KRAKEN2_DB_DIR"/data/SILVA_132_SSURef_Nr99_tax_silva.fasta \
   centrifuge_16s_db/silva_16s 2> centrifuge_build.log

**Comment by mbhall88** [comment]
Ah, this seems to have worked! So the `-c` argument doesn't work then? Might be good to clarify this in the help menu of `centrifuge-build`?
```
Options:
    -c                      reference sequences given on cmd line (as
                            <reference_in>)
```
Thank you again for your help!

@gabyrech if you follow the steps I did in this issue you can build the 16S SILVA database.

**Comment by gabyrech** [comment]
Great! Thanks @mbhall88 and @mourisl ! I'll give a try!
Best.
Gabriel
