### ISSUE TITLE
parameter to produce one taxonomy ID per sequence

### ISSUE THREAD

**Issue by derekguan** [infphilo/centrifuge#16]
Hi,
I am trying to use Centrifuge to complete metagenomics project, I only need one taxonomy ID for each read, however there are too many of them. And I have no idea which parameter could take control of how many taxonomy IDs a read could output. Could you please show which parameter could limit the number of output taxonomy id? 

Thanks a lot.

**Comment by mourisl** [comment]
One option to use parameter "-k 1".
As a result, more reads would be assigned to higher-level in the taxonomy tree comparing using default -k value. But some reads might be assigned to totally different branch in the taxonomy tree. We will make the result more consistent when changing "-k" value in future version. 
Is this what you need? Thanks.

**Comment by derekguan** [comment]
Thanks a lot, that's exactly what I need.

**Comment by derekguan** [comment]
Hi,

I have met another problem while running centrifuge with "-k 1", It seems that not all reads have a corresponding taxonomic id in result file, I think centrifuge doesn't output those reads with bad classification result, however I need those reads appear in result file, so is there a way to output all reads into classification file even though some of them may not have a taxonomic id?  

Thanks

**Comment by mourisl** [comment]
This feature is not implemented in current version. 
You can use "--reorder" option to force the output to have the same order as the input fasta/q file. Then you can figure out the unassigned reads and modify the report accordingly.

**Comment by derekguan** [comment]
Hi,

Is there a way to print the classification time of centrifuge? 

Thanks
