### ISSUE TITLE
Encountered internal Centrifuge exception (#1)

### ISSUE THREAD

**Issue by gkumar09** [infphilo/centrifuge#22]
Hi, I am trying to download centrifuge on my system. However, I am getting the following error in the index building step:

command I am giving:
centrifuge-build -p 4 --conversion-table seqid2taxid.map --taxonomy-tree taxonomy/nodes.dmp --name-table taxonomy/names.dmp input-sequences.fna abc

Output:
Settings:
  Output files: "abv._.cf"
  Line rate: 7 (line is 128 bytes)
  Lines per side: 1 (side is 128 bytes)
  Offset rate: 4 (one in 16)
  FTable chars: 10
  Strings: unpacked
  Local offset rate: 3 (one in 8)
  Local fTable chars: 6
  Max bucket size: default
  Max bucket size, sqrt multiplier: default
  Max bucket size, len divisor: 4
  Difference-cover sample period: 1024
  Endianness: little
  Actual local endianness: little
  Sanity checking: disabled
  Assertions: disabled
  Random seed: 0
  Sizeofs: void_:8, int:4, long:8, size_t:8
Input files DNA, FASTA:
  input-sequences.fna
Warning: Empty fasta file: 'input-sequences.fna'
Warning: All fasta inputs were empty
Total time for call to driver() for forward index: 00:00:00
Error: Encountered internal Centrifuge exception (#1)

Thanks
Gaurav

**Comment by fbreitwieser** [comment]
Hi @gkumar09 , there is a warning message `Empty fasta file: 'input-sequences.fna'`
