### ISSUE TITLE
There is no "install" target in Makefile

### ISSUE THREAD

**Issue by tseemann** [infphilo/centrifuge#23]
```
% make install
make: *** No rule to make target `install'.  Stop.
```

This is using your latest public release and following your Install docs.

If this is fixed in HEAD can you please make a new release for packaging in Homebrew Science.

**Comment by tseemann** [comment]
Oh, I musunderstood "Genome Research version" meant the version for a publication.

**Comment by infphilo** [comment]
Although the current version of Centrifuge does not have `install` target, we do have it in our master branch here.  We'll try to release a new version of Centrifuge within a couple of weeks.

**Comment by tseemann** [comment]
Ok - but you Installation instructions on the current README.md tell people to run `make install prefix=/usr/local` right now :)
