### ISSUE TITLE
make error on downloading databases

### ISSUE THREAD

**Issue by jrherr** [infphilo/centrifuge#33]
I've been trying to get databases set up for centrifuge for a few weeks now and I've been casually banging my head against this problem.  I get the same error on two different Mac OSX Sierra machines.  I suspect it's a permission issue.  Seems that after the files are downloaded the data can't be written to the database.  I have tried to modify the makefile to use 'sudo' but none of my changes seen to work.

Here's my error message: 

```
Progress : [######################################--] 97% 5855/5983
make[1]: *** [reference-sequences/all-viral.fna] Error 1
make: *** [b_compressed+h+v] Error 2
```

Any help here would be appreciated!  Thanks!

**Comment by fbreitwieser** [comment]
Hi @jrherr , there was an issue that all downloads stopped when one failed. Should work now.
