### ISSUE TITLE
error in parsing UniVec?

### ISSUE THREAD

**Issue by voutcn** [infphilo/centrifuge#42]
The output of `centrifuge-download contaminants` looks like

```
gnl|uv  32630
gnl|uv  32630
gnl|uv  32630
gnl|uv  32630
gnl|uv  32630
gnl|uv  32630
gnl|uv  32630
gnl|uv  32630
gnl|uv  32630
gnl|uv  32630
gnl|uv  32630
gnl|uv  32630
gnl|uv  32630
gnl|uv  32630
gnl|uv  32630
gnl|uv  32630
gnl|uv  32630
gnl|uv  32630
gnl|uv  32630
gnl|uv  32630
gnl|uv  32630
gnl|uv  32630
gnl|uv  32630
gnl|uv  32630
gnl|uv  32630
gnl|uv  32630
gnl|uv  32630
gnl|uv  32630
...
```

**Comment by fbreitwieser** [comment]
`centrifuge-download` outputs the sequence ID to taxonomy ID mapping. In `centrifuge-build`, the ID of a sequence is the header up to the first space or the second pipe. As in UniVec (nearly) all headers start with `>gnl|uv|`, just that part is exported. But it's not an error - both the taxonomy mapping and the download should work as expected.
