### ISSUE TITLE
No examples for custom database

### ISSUE THREAD

**Issue by flashton2003** [infphilo/centrifuge#44]
Hello,

Not sure if this is the right place, but in your documentation, there are no examples in the 'Custom Database' section. Just a TODO list :-)

If you could add these in, that would be really useful.

Thanks!

Phil

**Comment by MrOlm** [comment]
I agree- this would be very helpful :)

**Comment by fbreitwieser** [comment]
Hi @flashton2003 and @MrOlm , sorry for the delay, now there is some explanation on how to build custom database at https://github.com/infphilo/centrifuge/blob/master/MANUAL.markdown

**Comment by flashton2003** [comment]
Great, thank you!
