### ISSUE TITLE
name,n_genomoes,genome_size,avg_size not resolved in Report file

### ISSUE THREAD

**Issue by deepthoughts** [infphilo/centrifuge#5]
Hi,
--report-file option seems to generate files with no name, genome_size or avg_size. 
I am attaching a sample report file. 

Thanks

[33T_centrifuge_report.txt](https://github.com/infphilo/centrifuge/files/116209/33T_centrifuge_report.txt)

**Comment by infphilo** [comment]
We just released the first version of Centrifuge if you'd like to give it a try.

**Comment by deepthoughts** [comment]
I am currently trying it out. Thanks for the response and making Centrifuge.
