### ISSUE TITLE
Specify taxonomic level

### ISSUE THREAD

**Issue by rprops** [infphilo/centrifuge#54]
Hi,

Is there any option to specify the taxonomic level at which to report the classification, or even the full lineage. Currently I'm getting only species/genus classifications which aren't really informative for assessing environmental metagenome bins.

Thanks,

Ruben

**Comment by davidvilanova** [comment]
+1

**Comment by jjscarpa** [comment]
I have the same question. 

Is "+1" an answer

**Comment by GeoMicroSoares** [comment]
+1

**Comment by FCMicrobes** [comment]
+1

**Comment by mourisl** [comment]
Centrifuge assigns the reads to the lowest possible taxonomy level. I just uploaded a script "centrifuge-promote" that promote the taxonomy level to user-specified level.

centrifuge-promote takes three parameters in the order of: prefix of the index, centrifuge output file, taxonomy level. For example, you can run it like:
`./centrifuge-promote p_compressed centrifuge_output.txt family > centrifuge_output_family.txt`

There may be some assignments associated with taxonomy who can't trace to the specified taxonomy level or already higher than that level. In that case, I does not change their output information.
