### ISSUE TITLE
Examples in Manual missing 'refseq'

### ISSUE THREAD

**Issue by sandrobe-nih** [infphilo/centrifuge#55]
FYI, the examples below appear to be missing 'refseq' at the end before the '>>'.

Just stepping through.

Thanks,
Bob

    # download mouse and human reference genomes
    centrifuge-download -o library -d "vertebrate_mammalian" -a "Chromosome" -t 9606,10090 -c 'reference genome' >> seqid2taxid.map
    # only human
    centrifuge-download -o library -d "vertebrate_mammalian" -a "Chromosome" -t 9606 -c 'reference genome' >> seqid2taxid.map
    # only mouse
    centrifuge-download -o library -d "vertebrate_mammalian" -a "Chromosome" -t 10090 -c 'reference genome' >> seqid2taxid.map

**Comment by fbreitwieser** [comment]
Thanks for the info!
