### ISSUE TITLE
centrifuge-kreport doesn't exist

### ISSUE THREAD

**Issue by DNAsaurus** [infphilo/centrifuge#58]
Just as the title says.

Only the following exist:
`centrifuge                         centrifuge-build-bin-debug         centrifuge-class-debug             centrifuge-inspect                 centrifuge-RemoveEmptySequence.pl
centrifuge-build                   centrifuge-BuildSharedSequence.pl  centrifuge-compress.pl             centrifuge-inspect-bin             centrifuge-RemoveN.pl
centrifuge-build-bin               centrifuge-class                   centrifuge-download                centrifuge-inspect-bin-debug       centrifuge-sort-nt.pl`

**Comment by bioinfonm** [comment]
It only exists when you download from the github repo. The source and OS X binaries are missing it. Even after building from the github repo centrifuge-kreport doesn't run. I am opening a new issue for this.

**Comment by DNAsaurus** [comment]
Thanks for pointing it out. I was using the linux binaries, it also isn't there. I expected the repositories to be the same but I guess it never hurts to check...

Also yup, getting the same error as you are. 
You can just run it straight, I didn't have to build it. If you saved the path to the databases as an env variable you don't have to move any files.

**Comment by bioinfonm** [comment]
You are welcome. Sorry about getting the same error. 

I opened a new issue with the error. Hopefully if I have time this afternoon I'll look at the code to see if it's something I can fix.
