### ISSUE TITLE
Problem uncompressing p+h+v.tar.gz

### ISSUE THREAD

**Issue by jjscarpa** [infphilo/centrifuge#59]
Greetings, 

I am trying to determine if there is a problem with the p+h+v.tar.gz file. I get the following error after running the following commands:

$ wget ftp://ftp.ccb.jhu.edu/pub/infphilo/centrifuge/data/p+h+v.tar.gz
$ tar -zxvf p+h+v.tar.gz 

p+h+v.1.cf
p+h+v.2.cf

gzip: stdin: invalid compressed data--format violated
tar: Unexpected EOF in archive
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now

Looks like p+h+v.1.cf uncompresses fine but the command throws an error when moving to p+h+v.2.cf

I am on Ubuntu 14.04. I have tried downloading the tar.gz file several times. 
Thanks for any assistance

Jarrod

**Comment by metacrobe** [comment]
Any thoughts on this yet?

Related, I tried the following and it stalls at generating abv.3.cf. It looks like in it generates abv.1.cf fine (~349Mb), then abv.2.cf is a 0 bytes and the program hangs on abv.3.cf for days. Please, if you can give any advice it would be most appreciated.

`centrifuge-download -o taxonomy taxonomy
centrifuge-download -o library -m -d "archaea,bacteria,viral" refseq > seqid2taxid.map
cat library/*/*.fna > input-sequences.fna
centrifuge-build -p 4 --conversion-table seqid2taxid.map --taxonomy-tree taxonomy/nodes.dmp --name-table taxonomy/names.dmp input-sequences.fna abv
`

**Comment by bioinfonm** [comment]
Oh I've tried a few different versions of ftp-ing the database files down. And they all end up with the Unexpected EOF in archive error.

However direct download of the databases from the centrifuge website works fine.

**Comment by metacrobe** [comment]
Thank you for the response bioinfonm. I tried a straight download from this website (https://ccb.jhu.edu/software/centrifuge/), specifically  Bacteria, Aarchaea, Viruses, Human under Indexes. The link is does point to the FTP site. Is there another website where I can download the file?

I run
`tar -zxvf p+h+v.tar.gz `

and still get 

`p+h+v.1.cf
p+h+v.2.cf

gzip: stdin: invalid compressed data--format violated
tar: Unexpected EOF in archive
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now
`

**Comment by bioinfonm** [comment]
metacrobe so far I've tested just the _Bacteria, Archaea (compressed)_ and I am downloading _Bacteria, Aarchaea, Viruses, Human_ and will test that as soon as I have it.

I am pulling my indices from: http://www.ccb.jhu.edu/software/centrifuge/manual.shtml#obtaining-centrifuge

under the Indexes section.

**Comment by bioinfonm** [comment]
So just to test on the p_compressed.tar.gz (_Bacteria, Archaea (compressed)_) I ran:
tar -zxvf p_compressed.tar.gz

and the native OS X version. Both worked.

I should have the  _Bacteria, Aarchaea, Viruses, Human_ in a few hours and will post here.

**Comment by bioinfonm** [comment]
@metacrobe I downloaded the _Bacteria, Aarchaea, Viruses, Human_ from the main website. It uncompressed just fine. I can run it with some reduced metagenomes with no problem. I get kill -9 error if the input fasta files are to big.

**Comment by metacrobe** [comment]
@bioinfonm Thanks for testing this. Looks like it worked totally fine for you but even when I download the files directly from the website from the links (see attached image, these are ftp addresses) I still get the same results:

p_compressed+h+v.tar.gz stalls at 374Mb
p_compressed.tar.gz stalls at 372Mb
p+h+v.tar.gz dowloads completely but fails to extract. 

I have no idea what the problem could be but it sounds like it is me somehow???

![screen shot 2017-04-04 at 3 42 54 pm](https://cloud.githubusercontent.com/assets/16192182/24677790/a44c1f14-194d-11e7-8718-634688093ca2.png)

**Comment by bioinfonm** [comment]
Have you tried gnuzip or gzip?

**Comment by bioinfonm** [comment]
So tar -zxvf p+h+v.tar.gz works on OS X 10.11.6 for this index, just checked to make sure.

**Comment by bioinfonm** [comment]
@metacrobe  So maybe something like
gunzip p+h+v.tar.gz

then

tar -xvf p+h+v.tar
?

**Comment by metacrobe** [comment]
I am on ubuntu 14.04 and  have been using
`tar -zxvf p+h+v.tar.gz`

but I will try gnuzip, gzip, and guzip now

**Comment by bioinfonm** [comment]
Also just a heads up the p+h+v index doesn't seem to pick up viral sequences for some reason. They show up with kraken and hmmer databases but centrifuge plus p+h+v yields zero viral hits.

**Comment by metacrobe** [comment]
hum. odd but good to know--thanks.

I have tried everything I could think of but nothing works. I will keep plugging away. Thank you for your help @bioinfonm

**Comment by dfornika** [comment]
I'm having a similar problem decompressing the nt_2018_2_12.tar.gz file (ftp://ftp.ccb.jhu.edu/pub/infphilo/centrifuge/data/nt_2018_2_12.tar.gz)

I get an error message:

```
gzip: nt_2018_2_12.tar.gz invalid compressed data--format violated
```

I'm using gzip 1.5 on CentOS 7.

The sha256 sum of my file is:

```
0616989369e377ceb1f4da54264592408ac9a28ccd296b2de0527d3660c2afdf
```

**Comment by mourisl** [comment]
Our system says the sha256 sum for  nt_2018_2_12.tar.gz  is 73ee5e19fa68092f83e5b9f2ef083aabd619243010a14b68c5b7f6472be4fe89 .

**Comment by dfornika** [comment]
@mourisl Thanks, that might explain our problem. Were you able to decompress and untar the file?

Maybe the authors could publish checksums alongside their copies to help us confirm that we've got identical files after downloading.

**Comment by mourisl** [comment]
Yes, I created those tar files so the checksum should be correct. And I will add those checksums to our webpage.

**Comment by mourisl** [comment]
There is a md5 checksum file below the link to download the pre-built indices now. If the uncompresing issue still happens even though the checksum matches, please let us know.

**Comment by dfornika** [comment]
I can confirm that I re-downloaded the `nt_2018_2_12.tar.gz` file (using `wget`), checked the md5 sum and successfully uncompressed the file. Thanks.
