### ISSUE TITLE
Unaligned reads output (--un)

### ISSUE THREAD

**Issue by smolkmo** [infphilo/centrifuge#6]
Hi Daehwan,

Just wanted to notify you about a minor thing I noticed: While there were reads missing from the main Centrifuge output (supposedly unaligned?), the file for unaligned reads specified with the --un option remained empty.

Personally not an issue for me, since it was easy to find out the unaligned reads by other means.

Cheers,
Moritz

**Comment by infphilo** [comment]
Hi Moritz,

Thanks! I thought --un worked, but it doesn't.  We'll fix it and release the next version with some additional functionalities.

Thanks,
Daehwan

**Comment by stefjanson** [comment]
Hi,

--un still doesn't work, how did you get the unaligned reads? I work with big fasta files and cant find a fast method.

Greetings,
Stef

**Comment by feltzmc** [comment]
Hi Florian/Daehwan,

At my last testing, --un still isn't working.  When I attempt to use it centrifuge crashes.  I can post the error if it might be helpful.  Is this still something that will be implemented?

Thanks,
Matt

**Comment by mourisl** [comment]
Can you try to use "--un-conc" option in case your data set is paired-end reads. And to output the sequence of those unclassified reads, you have to use --tab-fmt-cols to let Centrifuge output the sequence and quality score of the reads (the option "--out-fmt sam" also works).

**Comment by feltzmc** [comment]
Hi Li,

Thank you for the quick response.  My data is unpaired and I can't seem to get either of those format options to work.  Here are the commands I am running:

This command runs great:
 time centrifuge -t -p 16 -q --report-file NBC02_summary_report.tsv -S NBC02_class_results.txt -x abv /home/mfeltz/workdir/NBC02_trimmed.fq

This command throws errors about bitwise operators:
 time centrifuge -t -p 16 -q --un Unmapped_Reads.txt --report-file NBC02_summary_report.tsv -S NBC02_class_results.txt -x abv /home/mfeltz/workdir/NBC02_trimmed.fq
Result:
Argument "NZ_CP009627.1" isn't numeric in bitwise and (&) at /home/mfeltz/workdir/CENTRIFUGE/centrifuge/centrifuge line 496, <BT> line 38949.
Argument "NZ_CP009628.1" isn't numeric in bitwise and (&) at /home/mfeltz/workdir/CENTRIFUGE/centrifuge/centrifuge line 496, <BT> line 38951.
Argument "NZ_CP009628.1" isn't numeric in bitwise and (&) at /home/mfeltz/workdir/CENTRIFUGE/centrifuge/centrifuge line 496, <BT> line 38953.

This is with the --out-fmt option
time centrifuge -t -p 16 -q --out-fmt sam --report-file NBC02_summary_report.tsv -S NBC02_class_results.txt -x abv /home/mfeltz/workdir/NBC02_trimmed.fq
Result:
/home/mfeltz/workdir/CENTRIFUGE/centrifuge/centrifuge-class: unrecognized option '--out-fmt'

Here is with --tab-fmt-cols
time centrifuge -t -p 16 -q --tab-fmt-cols --report-file NBC02_summary_report.tsv -S NBC02_class_results.txt -x abv /home/mfeltz/workdir/NBC02_trimmed.fq
Result:
/home/mfeltz/workdir/CENTRIFUGE/centrifuge/centrifuge-class: unrecognized option '--tab-fmt-cols'

Please let me know if I am missing something obvious here.

Thank you,
Matt

**Comment by mourisl** [comment]
Hi Matt,

  Is your version of centrifuge up-to-date? In the repository of github, the line 496 of the wrapper file "centrifuge" does not have any bit operation. And centrifuge-class should recognize those two options.

Li

**Comment by feltzmc** [comment]
Hi Li,

My apologies, my version was in fact out of date and that should have been the first thing I checked.  I just tested the command using the --un option after downloading the newest version and it works like a charm.  Thank you very much for your help and thanks for creating such a great tool.

Matt
