### ISSUE TITLE
make v 

### ISSUE THREAD

**Issue by klahmers1** [infphilo/centrifuge#64]
I have been trying to build databases and get this Error 2 result.  

$ make v
Making: v: v
/Library/Developer/CommandLineTools/usr/bin/make -f Makefile IDX_NAME=v
[[ -d tmp_v ]] && rm -rf tmp_v; mkdir -p tmp_v
Downloading and dust-masking viral-any_level
centrifuge-download -o tmp_v  -m -d "viral-any_level" -P 1 refseq > \
		tmp_v/all-viral-any_level.map
viral-any_level is not a valid domain - use one of the following:
  archaea
  bacteria
  fungi
  invertebrate
  plant
  protozoa
  vertebrate_mammalian
  vertebrate_other
  viral
make[1]: *** [reference-sequences/all-viral-any_level.fna] Error 1
make: *** [v] Error 2

What should I modify?

**Comment by hmontenegro** [comment]
Try with:

`make COMPLETE_GENOMES=viral IDX_NAME=v`

**Comment by laserson** [comment]
Same issue for me.  Why does the name munging fail for the `$(REFERENCE_SEQUENCES_DIR)/all-%-any_level.fna` target?
