### ISSUE TITLE
Error when running centrifuge-download

### ISSUE THREAD

**Issue by jvollme** [infphilo/centrifuge#67]
when trying to use centrifuge-download for creating the centrifuge database, using this command (taken from the example in the manual)...

`centrifuge-download -o library -m -d "archaea,bacteria,viral" refseq > seqid2taxid.map`

...I keep running into this error:

```
Downloading ftp://ftp.ncbi.nlm.nih.gov/genomes/refseq/archaea/assembly_summary.txt ...
rsync: failed to connect to ftp.ncbi.nlm.nih.gov (130.14.250.10): Connection timed out (110)
rsync: failed to connect to ftp.ncbi.nlm.nih.gov (2607:f220:41e:250::10): Network is unreachable (101)
rsync error: error in socket IO (code 10) at clientserver.c(122) [Receiver=3.0.9]
rsync Download failed! Have a look at valid domains at ftp://ftp.ncbi.nlm.nih.gov/genomes/refseq .
```
Is this a problem on my side? My Institutes connection does not go over a proxy (anymore), so I don't think this is a proxy problem.

**Comment by beaker888** [comment]
I keep running into the same issue. I can manually download with wget to the same ftp address, but the centrifuge-download command keeps timing out.

**Comment by fbreitwieser** [comment]
Thanks for the info. I'll add an option for the download method to the CLI
to use wget or curl instead of rsync.

**Comment by FCMicrobes** [comment]
I am facing the same issue. After a few downloads it stops with the same error.

$centrifuge-download -o taxonomy taxonomy
Downloading NCBI taxonomy ...
nodes.dmp
names.dmp
$centrifuge-download -o Any -a Any -m -d "fungi" refseq > seqid2taxid.map
#fungal genomes at Any assembly level from refseq
#Download
Downloading ftp://ftp.ncbi.nlm.nih.gov/genomes/refseq/fungi/assembly_summary.txt ...
Downloading 249 fungi genomes at assembly level Any ... (will take a while)
Progress : [######----------------------------------] 16% 41/249
Error downloading rsync://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/001/773/325/GCF_001773325.1_ASM177332v1/GCF_001773325.1_ASM177332v1_genomic.fna.gz!
rsync: failed to connect to ftp.ncbi.nlm.nih.gov: Network is unreachable (101)
rsync error: error in socket IO (code 10) at clientserver.c(124) [receiver=3.0.6]

Any idea how to solve this?

**Comment by beaker888** [comment]
Unfortunately I didn't find a direct solution, but our group was updating our programs to use Docker and this fixed the issue, as only curl was installed image.

**Comment by FCMicrobes** [comment]
Thks for the info. I was able to "solve" it by modifying the code to use wget...

**Comment by isardi** [comment]
I having the same issue.  FCMicrobes, can you please share how you modified the code to use wget.  It is probably my only way to get it to work.
Thanks in advanced!!

**Comment by ryandamen** [comment]
I also had the same problem. When I looked into the code of centrifuge-download I saw that it has options for using ftp as well. I "solved" the problem by removing rsync using:
`sudo apt-get remove rsync`
the program automatically switches to ftp and is working now.

**Comment by FCMicrobes** [comment]
Hello,
I have changed the DL_PROG option at the beginning of the script so it only uses wget. @ryandamen 's option does the job as well. 

`
if hash rsync 2>/dev/null; then
        DL_PROG="wget -N --reject=index.html -qO"
        DL_MODE="https"
elif hash wget 2>/dev/null; then
        DL_PROG="wget -N --reject=index.html -qO"
        DL_MODE="https"
else
        DL_PROG="wget -N --reject=index.html -qO"
        DL_MODE="https"
fi
export DL_PROG DL_MODE
`
Just copy the centrifuge-download to another location and edit it using tool like vim. Then you will run the new version.

Hope this helps

Cheers

**Comment by isardi** [comment]
Thanks so much!!! It is running now

**Comment by fbreitwieser** [comment]
Please note that `centrifuge-download` now (finally) has the option to specify the download program with `-g`:
```
./centrifuge-download

centrifuge-download [<options>] <database>

ARGUMENT
 <database>        One of refseq, genbank, contaminants or taxonomy:
                     - use refseq or genbank for genomic sequences,
                     - contaminants gets contaminant sequences from UniVec and EmVec,
                     - taxonomy for taxonomy mappings.

COMMON OPTIONS
 -o <directory>         Folder to which the files are downloaded. Default: '.'.
 -P <# of threads>      Number of processes when downloading (uses xargs). Default: '1'

WHEN USING database refseq OR genbank:
 -d <domain>            What domain to download. One or more of bacteria, viral, archaea, fungi, protozoa, invertebrate, plant, vertebrate_mammalian, vertebrate_other (comma separated).
 -a <assembly level>    Only download genomes with the specified assembly level. Default: 'Complete Genome'. Use 'Any' for any assembly level.
 -c <refseq category>   Only download genomes in the specified refseq category. Default: any.
 -t <taxids>            Only download the specified taxonomy IDs, comma separated. Default: any.
 -g <program>           Download using program. Options: rsync, curl, wget. Default rsync (auto-detected).
 -r                     Download RNA sequences, too.
 -u                     Filter unplaced sequences.
 -m                     Mask low-complexity regions using dustmasker. Default: off.
 -l                     Modify header to include taxonomy ID. Default: off.
 -g                     Download GI map.
 -v                     Verbose mode
```

Sorry for the long wait for this fix.

**Comment by MeHelmy** [comment]
when using the command as follow:
`centrifuge-download -g wget -o taxonomy taxonomy`
It raises this error:
centrifuge-download: illegal option -- g
centrifuge-download: line 180: OPTARG: unbound variable
