### ISSUE TITLE
centrifuge-download fails to print output, returns exit code 1 when run in dumb terminal

### ISSUE THREAD

**Issue by taltman** [infphilo/centrifuge#75]
Out of habit, I often test out new software within an Emacs shell, which has a terminal type of 'dumb'. Evidently, this prevents centrifuge-download from working correctly. The call to `tput el` will fail, causing the entire script to fail silently. 

The script should check whether it is currently running within a terminal capable of fancier terminal manipulation commands. If not, it should gracefully fall back to simpler output formatting.

I haven't tested this yet, but this issue makes me suspect that this script might break if it (or a parent shell) is not attached to a terminal.

**Comment by fbreitwieser** [comment]
Thanks for the input! Fixed now, should work even in an Emacs shell.
