### ISSUE TITLE
Empty --un-conc and --al-conc files

### ISSUE THREAD

**Issue by feltzmc** [infphilo/centrifuge#77]
When running Centrifuge on metagenomic samples against the nt index using the following command:

```
centrifuge -t -p 16 -q --un-conc SAS_Unmapped.sam --al-conc SAS_Mapped.sam --out-fmt sam \
--report-file SAS_NT_summary_report.tsv -S SAS_NT_class_results.txt -x nt_idx/nt \
-1 Trimmed_SAS_1_Equalized.fq -2 Trimmed_SAS_2_Equalized.fq
```

the run finishes with no errors and all files are created.  The summary and class files are populated and correct, but the SAS_Unmapped.1&2.sam files and the SAS_Mapped.1&2.sam files are empty.  Any ideas on what could be causing this issue would be appreciated.

**Comment by hmontenegro** [comment]
Which version? I see [Make --un,--al,--un-conc,--al-conc work](https://github.com/infphilo/centrifuge/commit/df65b608667676110c0aa58a3ee7aa578911e2b6), a commit from Jan 13, 2017, thus not found on the latest (1.0.3b) release.

**Comment by feltzmc** [comment]
I am using the 1.0.3b release, however, according to the answer from @mourisl on issue #6 it seems like these should all be working in the latest release.  Also I have done several runs with unpaired data which generate the --un and --al output files correctly.

It is possible though that they managed to get the unpaired options working but left that commit in because the paired end options do not work.  Thanks for pointing it out.

**Comment by mourisl** [comment]
We put these update into 1.0.3 release. And these options should work in that release. Sorry for the late reply.
