### ISSUE TITLE
centrifuge-download outputs the string 'done' on stdout

### ISSUE THREAD

**Issue by sungenomics** [infphilo/centrifuge#78]
Hello,

As an example, I tried to download and index the whole archaea RefSeq database with Centrifuge.

To do so, I launch the following commands:
```
centrifuge-download library -d archaea -a 'Complete Genome' refseq > seqid2taxid.1.map
centrifuge-download library -d archaea -a 'Chromosome' refseq > seqid2taxid.2.map
centrifuge-download library -d archaea -a 'Scaffold' refseq > seqid2taxid.3.map
centrifuge-download library -d archaea -a 'Contig' refseq > seqid2taxid.4.map
```

The problem is I can't index the sequences I downloaded because there are some problems with the seqid2taxid files.

For example, I found the following results when I execute the `grep "done" *.map` command:

```
seqid2taxid.3.map:NZdone
seqid2taxid.3.map:NZdone
seqid2taxid.3.map:NZdone
seqid2taxid.4.map:NZdone
seqid2taxid.4.map:NZ_BANO01000065.done
seqid2taxid.4.map:NZdone
seqid2taxid.4.map:NZ_LOPV0100015done
seqid2taxid.4.map:NZ_MAIF0100015done
```

Do you have an idea where this problem come from ? Do I made a mistake ?

Thanks,
Thibaut

**Comment by sungenomics** [comment]
Hello,

Just for information, the problem seems to come from the end of the _download_n_process_ function with the command `echo done`.

Best,
Thibaut

**Comment by fbreitwieser** [comment]
Hi @ghost, I think this problem should be fixed in the latest version. Please feel free to re-open if the problem persists!
