### ISSUE TITLE
(ERR): centrifuge-class died with signal 11 (SEGV) 

### ISSUE THREAD

**Issue by jw22** [infphilo/centrifuge#8]
Hello,

Ops, I pressed the submit button to early for my previous request. 
Here I will also include the log file and the error message below. 
Could yo please let me know what is possible wrong.
I am using centrifuge-1.0.1-beta
Thanks very much,

Josef, 

[18512.C.pdf](https://github.com/infphilo/centrifuge/files/279653/18512.C.pdf)

report file study.18512
Number of iterations in EM algorithm: 8415
Probability diff. (P - P_prev) in the last iteration: 9.99892e-11
(ERR): centrifuge-class died with signal 11 (SEGV)

**Comment by infphilo** [comment]
This might have been fixed in the GitHub master version.  Would you like to give it a try and let me know?

**Comment by jw22** [comment]
Dear Daehwan,


Thanks for letting me know.
I am not completely sure where the master version.
Could you please point me into the right direction for the download.
I would like to try it out.

Thanks,
Josef


Dr Josef Wagner (PhD)
Senior Postdoctoral Research Fellow
Human Microbiomes and Metagenomics
Pathogen Genomics
Wellcome Trust Sanger Institute
Cambridge, UK

**Comment by fbreitwieser** [comment]
With master version he meant the latest github version. You can download the source and build the latest version with 

```
git clone https://github.com/infphilo/centrifuge
cd centrifuge
make all
```

**Comment by infphilo** [comment]
We just released a new version of Centrifuge if you'd like to use (see the Centrifuge webpage).

**Comment by jw22** [comment]
Dear Florian,
All clear,
Thanks very much

Josef

**Comment by jw22** [comment]
Dear Daehwan,

Thanks for letting me know about the latest version of centrifuge.

Josef

**Comment by fbreitwieser** [comment]
I presume this issue has been fixed. If you still have it, please feel free to reopen this issue.

**Comment by Cheyou** [comment]
Dear all,
When I use the following command, the problem (centrifuge-class died with signal 11 (SEGV)) is still exits. (centrifuge-class version 1.0.3-beta 64-bit)
centrifuge -f -x Test.fasta. 
When I tried the data in the example folder, there is no problem. So I want to know how to solve this problem.
Thank you!
@infphilo @fbreitwieser
