### ISSUE TITLE
offrate and large-index are missing from classifier and inspect

### ISSUE THREAD

**Issue by vesnapajic** [infphilo/centrifuge#80]
We have a problem running classifier with option --offrate. We keep getting an error with the message:
centrifuge-class: unrecognized option '--offrate'
However, this option is listed in description of the tool. Can you tell us is it supported in version 1.0.3 or not? 
The command was:
`centrifuge --report-file Centrifuge_report.tsv --offrate 10 -x fungi -U SRS065335.denovo_duplicates_marked.trimmed.singleton.fastq,SRS065335.denovo_duplicates_marked.trimmed.2.fastq,SRS065335.denovo_duplicates_marked.trimmed.1.fastq -q -S Classification_result.txt`

The similar situation is with option large-index and centrifuge-inspect.

**Comment by cdesjar** [comment]
Having the same problem (with version 1.0.3). Is there a solution or fix in the works for this? Thanks.

**Comment by mourisl** [comment]
The offrate option is not implemented. Centrifuge always works with large index, so the option of large-index is not used. I just removed these two options from the usage output. Sorry for the confusion.
