### ISSUE TITLE
Pair-end examples

### ISSUE THREAD

**Issue by lixin6135** [infphilo/centrifuge#81]
Hi,

Can you please give me some detail format example for **pair-end** fasta, because I can't find corresponding explanation on Manual?  I have following pair-end data as input, but it failed. I guess it may be the reads names or file names.

Failure report: 
```
Error: reads file does not look like a FASTA file
terminate called after throwing an instance of 'int'
(ERR): centrifuge-class died with signal 6 (ABRT) (core dumped)
```
My reads in forward file(a1_forward.fasta):
```
>r1.1 1 length=300
GCTGNNNNNNNNNNTGTTGAACATCTTCATGGACACGA
>r2.2 2 length=300
TTCTNNNNNNNNNNACTATGATCTGCCCGAAAATAC

```
My reads in reverse file(a1_reverse.fasta):
```
>r1.1 1 length=300
TTGCCGCTCGCTGGCCTCCTATCCGTACGTCTTCTGCTA
>r1.2 2 length=300
TCCTTCATATATTTCTGTATGTTTTGGTAGTAAGATTTTGTATTGAC

```

**Comment by mourisl** [comment]
Sorry for the late reply. I guess you did not use "-f" to explicitly specify the input is in fasta format? Centrifuge by default takes fastq format.
