### ISSUE TITLE
Version of the pre-compiled NCBI nt index

### ISSUE THREAD

**Issue by amphioxus** [infphilo/centrifuge#84]
This is not exactly an issue with centrifuge, but I couldn't find any information on what version (year) of the nt database was used for the pre-compiled index on the main web site (https://ccb.jhu.edu/software/centrifuge/manual.shtml).  Does anyone one know what version, or from what year, it is? It says it was last updated 12/06/2016, but I guess that doesn't necessarily mean the index is from 2016, right?

Many thanks for this fantastic tool, by the way!

**Comment by mourisl** [comment]
We've updated the nt database.

**Comment by harisankarsadasivan** [comment]
Is the NCBI nt index provided for download, a compressed index? Because some of my sequences from the NT genome reference database provided on website (the FTP link) does not align.
