### ISSUE TITLE
One result/report file per submitted input-file?

### ISSUE THREAD

**Issue by sschmeier** [infphilo/centrifuge#86]
When submitting multiple files with:

`
-U lane1.fq,lane2.fq,lane3.fq,lane4.fq
`

and using parameters:

`
-S <filename> --report-file <filename>
`

Is there an option to get one result and report file per input file? Mine seem to get overwritten?

Cheers,
Seb

**Comment by mourisl** [comment]
Centrifuge will concatenate the results in one file. If you want separate reports, you can just run 4 instances of Centrifuge.
