### ISSUE TITLE
--out-fmt option

### ISSUE THREAD

**Issue by ascendo** [infphilo/centrifuge#87]
Hello folks,

I have a simple question regarding --out-fmt options.
The default --out-fmt tab will not work with --un, --al, --al-con & etcs, I need to set it to sam for decontamination. Since "pavian" provides a fancy graph, I need to use  --out-fmt tab as well as centrifuge-kreport. The problem is that I set  --out-fmt option to tab, I cannot get the unmapped or mapped reads.

How can I get the output for unmapped or mapped reads and input for centrifuge-kreport at once ?
Currently my resolution is "running twice" with tab and sam.

Cheers,

Won

**Comment by mourisl** [comment]
I've upload a new version of kreport and it should handle your case.
