### ISSUE TITLE
(ERR): centrifuge-class died with signal 11 (SEGV) 

### ISSUE THREAD

**Issue by Cheyou** [infphilo/centrifuge#88]
Dear all,
When I use the following command, the problem (centrifuge-class died with signal 11 (SEGV)) is still exits. (centrifuge-class version 1.0.3-beta 64-bit)
centrifuge -f -x Test.fasta.
When I tried the data in the example folder, there is no problem. So I want to know how to solve this problem.
Thank you!
@infphilo @fbreitwieser

**Comment by mourisl** [comment]
-x should follow the index file not the read file.
