### ISSUE TITLE
Error in `centrifuge-class': munmap_chunk(): invalid pointer

### ISSUE THREAD

**Issue by tomazberisa** [infphilo/centrifuge#9]
After running the following command with 10 cores and 150GB of memory (of which 87.140GB were used) on CentOS Linux release 7.1.1503:
```
$CENTRIFUGE_HOME/centrifuge -q -x datasets/centrifuge/nt/nt -1 f1.R1.fastq -2 f1.R2.fastq
```
Centrifuge classifies sequences from the fastq files, but errors out when generating centrifuge_report.csv.

The error output is here:
[error.txt](https://github.com/infphilo/centrifuge/files/280087/error.txt)

Am I doing something wrong?

**Comment by infphilo** [comment]
I think we might have fixed this issue, and the fix is incorporated in the master branch.  Would it be possible for you to try the GitHub version?

**Comment by desalas** [comment]
Hi there,
I would like to receive some help. Our system administrator tried to install centrifuge and got Error 1 and Error 2. Please see the details of the errors below: 

/xxx/xxx/centrifuge/indices@node12> make p+h+v 
Making: p+h+v: p+h+v
make -f Makefile IDX_NAME=p+h+v
make[1]: Entering directory `/misc/xxx/software/centrifuge/indices'
mkdir -p reference-sequences
[[ -d tmp_p+h+v ]] && rm -rf tmp_p+h+v; mkdir -p tmp_p+h+v
Downloading and dust-masking archaea
centrifuge-download -o tmp_p+h+v  -m -d "archaea" -P 1 refseq > \
tmp_p+h+v/all-archaea.map
Downloading ftp://ftp.ncbi.nlm.nih.gov/genomes/refseq/archaea/assembly_summary.txt ...
Downloading 224 archaea genomes at assembly level Complete Genome ... (will take a while)
Progress : [####------------------------------------] 12% 28/224
Progress : [########################################] 100% 224/224
cat tmp_p+h+v/archaea/*.fna > reference-sequences/all-archaea.fna.tmp && mv reference-sequences/all-archaea.fna.tmp reference-sequences/all-archaea.fna
mv tmp_p+h+v/all-archaea.map reference-sequences/all-archaea.map
rm -rf tmp_p+h+v
[[ -d tmp_p+h+v ]] && rm -rf tmp_p+h+v; mkdir -p tmp_p+h+v
Downloading and dust-masking bacteria
centrifuge-download -o tmp_p+h+v  -m -d "bacteria" -P 1 refseq > \
tmp_p+h+v/all-bacteria.map
Downloading ftp://ftp.ncbi.nlm.nih.gov/genomes/refseq/bacteria/assembly_summary.txt ...
Downloading 6498 bacteria genomes at assembly level Complete Genome ... (will take a while)
Progress : [----------------------------------------] 0% 64/6498
Progress : [########################################] 100% 6498/6498
cat tmp_p+h+v/bacteria/*.fna > reference-sequences/all-bacteria.fna.tmp && mv reference-sequences/all-bacteria.fna.tmp reference-sequences/all-bacteria.fna
mv tmp_p+h+v/all-bacteria.map reference-sequences/all-bacteria.map
rm -rf tmp_p+h+v
[[ -d tmp_p+h+v ]] && rm -rf tmp_p+h+v; mkdir -p tmp_p+h+v
Downloading and dust-masking viral-any_level
centrifuge-download -o tmp_p+h+v  -m -d "viral-any_level" -P 1 refseq > \
tmp_p+h+v/all-viral-any_level.map
viral-any_level is not a valid domain - use one of the following:
  archaea
  bacteria
  fungi
  invertebrate
  plant
  protozoa
  unknown
  vertebrate_mammalian
  vertebrate_other
  viral
make[1]: *** [reference-sequences/all-viral-any_level.fna] Error 1
make[1]: Leaving directory `/misc/xxx/software/centrifuge/indices'
make: *** [p+h+v] Error 2
