### ISSUE TITLE
--al-gz is producing a sam with no line endings that samtools can not view

### ISSUE THREAD

**Issue by scottdaniel** [infphilo/centrifuge#90]
Hi,

I'm using centrifuge 1.0.3 beta like so:
```
centifruge -x centdb/p_compressed+h+v -1 reads.1.fq -2 reads.2.fq -U singletons.fq \
        -S $OUT_DIR/centrifuge_hits.tsv \
        --report-file $OUT_DIR/centrifuge_report.tsv \
        -fq \
        --exclude-taxids 9606 \
        --al-gz $OUT_DIR/bactvir_unpaired.sam.gz \
        --al-conc-gz $OUT_DIR/bactvir_paired.sam.gz \
        --threads 28
```

First, I get the paired.sam.gz (1 and 2) as empty, which is ok, I just figure they're all in the unpaired?

Second, the unpaired.sam.gz when I
`zcat bactvir_unpaired.sam.gz > test.sam` 

and I
`samtools view test.sam | head`

I get:
```
[W::sam_read1] Parse error at line 1
[main_samview] truncated file.
```

Also, when I 
`file test.sam`
I get: `test.sam: ASCII C++ program text, with very long lines, with no line terminators`

And `head test.sam` looks a bit like this:
```
UNC13-SN749:201:C15RYACXX:1:2305:20624:130441	cid|55508	55508	100	0	25	48	1UNC13-SN749:201:C15RYACXX:1:2306:15250:155736	family	1198451	144	144	27	48	5UNC13-SN749:201:C15RYACXX:1:2306:15250:155736	genus	2192	144	144	27	48	5UNC13-SN749:201:C15RYACXX:1:2306:15250:155736	genus	101191	144	144	27	48	5UNC13-SN749:201:C15RYACXX:1:2307:3308:73167	cid|55508	55508	64	0	23	48	1UNC13-SN749:201:C15RYACXX:1:2307:3480:108115	cid|1644130	1644130	196	196	29	48	2UNC13-SN749:201:C15RYACXX:1:2307:12906:29061	cid|55508	55508	81	0	24	48	1UNC13-SN749:201:C15RYACXX:1:2307:20820:74808	cid|55508	55508	289	0	32	48	1UNC13-SN749:201:C15RYACXX:1:2307:21370:107795	cid|1391653	1391653	64	0	23	48	1UNC13-SN749:201:C15RYACXX:1:2308:10627:2544	cid|170861	170861	64	0	23	48	1UNC13-SN749:201:C15RYACXX:1:2308:21201:128971	cid|128	128	144	144	27	48	5UNC13-SN749:201:C15RYACXX:1:2308:21201:128971	cid|119	119	144	144	27	48	5UNC13-SN749:201:C15RYACXX:1:2308:21201:128971	cid|466153	466153	144	144	27	48	5
```
i.e. exactly what the `file` command is telling me... so, any help? Thanks.

Attached is the run log from one of the runs (I was analyzing about 164 samples).
[example.log](https://github.com/infphilo/centrifuge/files/1515156/example.log) < the full log was 11mb so I truncated the middle part because it was just more of the same

**Comment by mourisl** [comment]
You need to use option "--out-fmt sam" option to let the "--al, --al-conc" options work. Furthermore, the files specified in "al, al-conc" will be in fastq format (the reads that are classified or not classified), not in sam format.

**Comment by scottdaniel** [comment]
Ok thanks, I will do the `--out-fmt sam` option but I'm a little confused. Even with that option enable the aligned / classified reads (the only ones I want) will still come out as fastq format? (i.e. bactvir_unpaired.fastq)

**Comment by mourisl** [comment]
The out-fmt only controls the format of the Centrifuge report file. "--al, --al-conc" is to obtain the raw reads' sequence, so the corresponding files are in fastq format.

**Comment by scottdaniel** [comment]
Ok, that works... just a suggestion, but it might be helpful to include 

> You need to use option "--out-fmt sam" option to let the "--al, --al-conc" options work. Furthermore, the files specified in "al, al-conc" will be in fastq format

In the Manual. Or some similar verbiage. Thanks.

**Comment by scottdaniel** [comment]
Still having issues:
I'm using `--out-fmt sam` and `--al unpaired.fq`.

The centrifuge_hits AND the unpaired are both SAM files. The only difference is that the "unpaired.fq" does not have line endings. It just means an extra step for me to convert the centrifuge_hits to fastq file(s).

**Comment by mourisl** [comment]
Did you download the release version or cloned the git repo? The support for the "--al, --al-conc" are added after the release.

**Comment by scottdaniel** [comment]
Crap, I did download the release version... will try with the source from the github repo

**Comment by mourisl** [comment]
We just uploaded a finalized implementation for the options "--al, --al-conc". You don't need to use "--out-fmt sam" in this implementation and can directly use "--al, --al-conc,..." options.

**Comment by scottdaniel** [comment]
Thanks, I'll try it out

**Comment by scottdaniel** [comment]
It just keep getting weirder...
I tried it with options like so:
   ```
$cent -x $SING_CENT/$DB -1 $R1 -2 $R2 -U $S\
        -S $OUT_DIR/centrifuge_hits.tsv \
        --report-file $OUT_DIR/centrifuge_report.tsv \
        -$FILE_TYPE \
        --exclude-taxids $EXCLUDE \
        --al $OUT_DIR/bactvir_unpaired.fq \
        --al-conc $OUT_DIR/bactvir_paired.fq \
        $THREADS
```
and it did output fastq files... but they are only 48bp long, weird
```
-bash-4.1$ head bactvir_unpaired.fq
@UNC12-SN629:265:C1Y68ACXX:7:1101:9034:175564
CGCTGCTGTTGCTGCTGTTGTTGCTGCTGTTGTTGCTGCTGTTGCTGC
+
B@@FFFFFHHHHHJJJIHIJIIIAAHHCH+CFF=DGGI>FH?FD9?B3
@UNC12-SN629:265:C1Y68ACXX:7:1101:10403:51990
AATGCAACAACCAATAATATTTACTGAATTCAAACTATTTACTTGTAA
+
=?BD7ADDBFB;FFECB@?HDHB?AC@FEIJADGCADDHDFG>HDHE@
@UNC12-SN629:265:C1Y68ACXX:7:1101:12470:22319
ATCCAGCTGCCCCAGCTGCTCCAAGAGGTCATTAATAATGCTGAGGAG
```
I can reopen a new issue if you need since this one has been sort of fixed

**Comment by mourisl** [comment]
Can you show me first several lines of the input fastq file?

**Comment by scottdaniel** [comment]
Sorry, this was my mistake. Apparently, I have a data set with mixed read lengths (48, 76 and 97bp).
