### ISSUE TITLE
From centrifuge output to tsv

### ISSUE THREAD

**Issue by Anuravi123** [infphilo/centrifuge#91]
This is the command I use to run centrifuge
centrifuge -x /mnt/volume_4/centrifuge/custom_databases/p+h+v -1 ../536_forward.fq.gz -2 ../536_reverse.fq.gz -S ./536_1 --report-file 536.tsv -q

Strangely, I get a output file as 536_1 but I dont get the tsv file. Is there anyway of transforming the output file to  tsv file without having to run the analyses all over again

Thanks!

**Comment by mourisl** [comment]
Did you get centrifuge_report.tsv in the directory?

**Comment by Anuravi123** [comment]
Hello

No I didn’t get the centrifuge_report.tsv either. I will try running this again tomorrow

Anu

**Comment by mourisl** [comment]
How is the re-running result?
