### ISSUE TITLE
Failure of centrifuge-kreport

### ISSUE THREAD

**Issue by apredeus** [infphilo/centrifuge#92]
Hello, 

I got the following error when trying to generate a Pavian-compatible report: 

`centrifuge-kreport -x <DB> centrifuge.report.csv > pavian.report.csv`

> Loading taxonomy ...
> Loading names file ...
> Loading nodes file ...
> Use of uninitialized value $numMatches in division (/) at /pub41/alexb/miniconda2/bin/centrifuge-kreport line 80, <> line 2.
> Illegal division by zero at /pub41/alexb/miniconda2/bin/centrifuge-kreport line 80, <> line 2.

I'm using version 1.0.3-beta I got from bioconda.

**Comment by apredeus** [comment]
The one that I freshly cloned and compiled also generates errors:

> Loading taxonomy ...
> Loading names file ...
> Loading nodes file ...
> Use of uninitialized value $headerMap{"seqID"} in array element at /pub41/alexb/centrifuge/centrifuge-kreport line 89, <> line 2.
> Use of uninitialized value $headerMap{"score"} in array element at /pub41/alexb/centrifuge/centrifuge-kreport line 91, <> line 2.
> Use of uninitialized value $headerMap{"hitLength"} in array element at /pub41/alexb/centrifuge/centrifuge-kreport line 92, <> line 2.
> Use of uninitialized value $headerMap{"queryLength"} in array element at /pub41/alexb/centrifuge/centrifuge-kreport line 93, <> line 2.
> Use of uninitialized value $headerMap{"numMatches"} in array element at /pub41/alexb/centrifuge/centrifuge-kreport line 94, <> line 2.
> Argument "root" isn't numeric in division (/) at /pub41/alexb/centrifuge/centrifuge-kreport line 99, <> line 2.
> Illegal division by zero at /pub41/alexb/centrifuge/centrifuge-kreport line 99, <> line 2.

**Comment by apredeus** [comment]
My bad, I was using the centrifuge summary instead of the full classification table.

**Comment by karoraw1** [comment]
I tried it on both files and got the same illegal division by zero error, but only that single error line. 

When I used it on the correct file (i.e. the one produced by the -S flag), the following was returned: 
```
$ centrifuge-kreport -x $CENT_BASE/p+h+v/p+h+v Assemblies/test_runs/062309.cfg_hits.tsv > 062309.kreport.txt
Loading taxonomy ...
Loading names file ...
Loading nodes file ...
Illegal division by zero at /work/Keith_Files/kaw/CENTRIFUGE/centrifuge/centrifuge-kreport line 77, <> line 365.
```

I attached the file that I'm trying to convert (I changed the file extension to one GitHub allowed me to use for an upload)

[062309.cfg_hits.tsv.txt](https://github.com/infphilo/centrifuge/files/1627688/062309.cfg_hits.tsv.txt)

**Comment by mourisl** [comment]
Is your centrifuge-kreport most up-to-date? I just tested it on our system and it worked fine. In the new centrifuge-kreport, line 77 does not correspond to any computation.

Thanks,
Li

**Comment by karoraw1** [comment]
updating fixed the problem. THANKS!
