### ISSUE TITLE
centrifuge-build doesn't find tax id in the map file

### ISSUE THREAD

**Issue by vrmarcelino** [infphilo/centrifuge#93]
Hi all,

I’m trying to build an index from the ncbi nt database.
I’ve downloaded the nucl_gb.accession2taxid.gz, and produced a .map file that should be mimicking the gi_taxid_nucl.map (but instead of GI’s we have accession numbers):

Ex:
gi|A00002.1	9913
gi|A00003.1	9913
gi|X17276.1	9646

When I try to build the index, it doesn’t find the corresponding taxonomy ID of any of the sequences:

Ex:
```
Warning: taxomony id doesn't exists for X14906.1!
Warning: taxomony id doesn't exists for X14907.1!
Warning: taxomony id doesn't exists for X14908.1!
```

Even though their IDs are in the .map file:
```
grep X14906.1 accession_taxid_nucl.map
gi|X14906.1	9913
```

I’ve also checked that the tax id 9913 is in the nodes.dmp and in the names.dmp files. Any ideas on what is happening here?

Thanks!

**Comment by mourisl** [comment]
Can you try to remove all the "gi|" prefix in all the entries of .map file? 

Thanks,
Li

**Comment by vrmarcelino** [comment]
Thanks for the quick reply!

Yes, removing the "gi|" did the trick, it is working now!

Thank you!
