### ISSUE TITLE
Missing Alignments

### ISSUE THREAD

**Issue by evolarium** [infphilo/centrifuge#94]
Hi:

I've been running some tests with centrifuge and I am seeing unclassified reads that are 100% matches to sequences in the database.  I'm wondering if there is a reason why they wouldn't be found, or if I am seeing a bug.

For example, using the nt database provided on the centrifuge web site and the current master version of centrifuge (5c51ac6851d40f3ac34d7b0c0834503698b10647) the following read is unclassified.

```
>read1
GCCCACTGTAAAGCTAACTTAGCATTAACCTTTTAAGTTAAAGATTAAGAGAACCAACACCTCTTTACAGTGAAATGCCCCAACTAAATACTACCGTATGGCCCACCATAATTACCCCCATACTCCTTACACTATTCCTCATCACCCAAC
```

It has a full-length 100% identity match to KC533490.1, which I've verified is in the centrifuge nt database with centrifuge-inspect.

**Comment by mourisl** [comment]
The reverse complement of this read also have 100% identity match to the nt database, which suggests that this read is from a repeat region. If a hit hits too many places (specified by the -k option), Centrifuge will not use that hit to classify the read. In this case, we only have one hit, and it hits too many places, hence this read is not classified.
