### ISSUE TITLE
Centrifuge misassigns some reads

### ISSUE THREAD

**Issue by jsh58** [infphilo/centrifuge#97]
Centrifuge misassigns some reads that align near the beginning of one reference sequence.  The incorrect assignment is to the previous reference sequence in the database.

I have observed this with the nt database, but I will illustrate here with a toy example:

##### reference database:
```
>seq_A
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
>seq_B
GCGTAGCCAGTAGCAGGACTTTACCGTGCGGTACAAGCCTACAGACCGATTA
```
##### query sequences (each 25-mer of `seq_B`, from "qseq0" to "qseq27"):
```
@qseq0
GCGTAGCCAGTAGCAGGACTTTACC
+
IIIIIIIIIIIIIIIIIIIIIIIII
@qseq1
CGTAGCCAGTAGCAGGACTTTACCG
+
IIIIIIIIIIIIIIIIIIIIIIIII
[...]
@qseq27
GCGGTACAAGCCTACAGACCGATTA
+
IIIIIIIIIIIIIIIIIIIIIIIII
```

#### results:
Centrifuge incorrectly assigns the first 15 reads to `seq_A`.  Here is the output:
```
readID	seqID	taxID	score	2ndBestScore	hitLength	queryLength	numMatches
qseq0	seq_A	0	100	0	25	25	1
qseq1	seq_A	0	100	0	25	25	1
qseq2	seq_A	0	100	0	25	25	1
qseq3	seq_A	0	100	0	25	25	1
qseq4	seq_A	0	100	0	25	25	1
qseq5	seq_A	0	100	0	25	25	1
qseq6	seq_A	0	100	0	25	25	1
qseq7	seq_A	0	100	0	25	25	1
qseq8	seq_A	0	100	0	25	25	1
qseq9	seq_A	0	100	0	25	25	1
qseq10	seq_A	0	100	0	25	25	1
qseq11	seq_A	0	100	0	25	25	1
qseq12	seq_A	0	100	0	25	25	1
qseq13	seq_A	0	100	0	25	25	1
qseq14	seq_A	0	100	0	25	25	1
qseq15	seq_B	0	100	0	25	25	1
qseq16	seq_B	0	100	0	25	25	1
qseq17	seq_B	0	100	0	25	25	1
qseq18	seq_B	0	100	0	25	25	1
qseq19	seq_B	0	100	0	25	25	1
qseq20	seq_B	0	100	0	25	25	1
qseq21	seq_B	0	100	0	25	25	1
qseq22	seq_B	0	100	0	25	25	1
qseq23	seq_B	0	100	0	25	25	1
qseq24	seq_B	0	100	0	25	25	1
qseq25	seq_B	0	100	0	25	25	1
qseq26	seq_B	0	100	0	25	25	1
qseq27	seq_B	0	100	0	25	25	1
```
All 28 reads should have been assigned to `seq_B`.

**Comment by mourisl** [comment]
This seems happen to the reference in the database that are very short. We will look into this issue.

**Comment by jsh58** [comment]
@mourisl 
Thanks.  That certainly works better, at least with my toy example.  Although, reads that span between two reference sequences, even by a single nucleotide, are always assigned to the previous reference.  For example:
```
@qseq
AGCGTAGCCAGTAGCAGGACTTTAC
+
IIIIIIIIIIIIIIIIIIIIIIIII
```
is assigned to seq_A, despite being 96% seq_B:
```
qseq	seq_A	0	100	0	25	25	1
```

**Comment by mourisl** [comment]
Yes, that is my next goal. (One problem at a time :) ).

**Comment by mourisl** [comment]
So for the case of a hit span between two reference sequences, I adopt a compromise implementation. If the span to the previous ref genome is less than 12 bp, it will be classified to the next ref genome. Otherwise, it will still be classified the previous ref genome. 
Ideally, the hit should be split into two parts if it spans different ref genomes. But the scenario that the hit has long anchors on both reference is not likely to happen in real and too difficult to implement under current structure. I think this compromise is reasonable. 
Does this help?

**Comment by jsh58** [comment]
@mourisl 
That is certainly better.  But, what about a 100bp read that aligns to two references 12bp/88bp?

Perhaps, it would be better to classify a read based on where its middle nucleotide matches (or, the middle nucleotide of its matching span).  That way, we would be assured that the assignment is to the reference that has the longest match.  I do not know how difficult that would be to implement, though.

You are correct that it is rare for a read to span two references, especially from different taxa.  In my case, I have been experimenting with appending sequence contaminants (e.g. adapters) to the database, and in this case it does occur somewhat frequently.

**Comment by mourisl** [comment]
By the nature of the data structure, it would be very difficult to implement that and probably would make the program much slower. Considering it won't happen in most of the scenarios, I don't feel it is good to use middle nucleotide to get the ref id. 

For your case, you can also prepend some sequences to the database and that should solve the problem.

**Comment by jsh58** [comment]
@mourisl 
OK, I understand.  Any chance of incorporating the code changes into a new release/version in the main branch?

**Comment by mourisl** [comment]
Absolutely. I'm testing it on larger database now.

**Comment by mourisl** [comment]
After testing the code on many cases and improving the speed, I just merge the changes to the master branch. 

Thanks for pointing out the issue.

**Comment by jsh58** [comment]
@mourisl 
Thanks again for the code changes.

I tested the code as of commit `ed5154ff52255ff1065391ac7ce7f98c6c671d2f` (dated Mar 1) and did not find any problems with misassigning reads.

However, later commits in the `boundary` branch, such as `b990d27b234a65341dd2b686a993985fb1540e4b` (dated Mar 22), produce some of the same errors outlined above.  Unfortunately, the same is true for the code that was incorporated into the current `master` branch.

**Comment by mourisl** [comment]
Did you test it on the toy example as the first post here? I just tested it again and did not see any wrong assignment.

**Comment by mourisl** [comment]
Have you tried the commit "68271abb4f7bcf8daf350887661cd4c79cb9f821" ?

**Comment by jsh58** [comment]
Yes, that commit has the same problems.

**Comment by jsh58** [comment]
No, the index was built under commit `ed5154ff52255ff1065391ac7ce7f98c6c671d2f`.  I will try rebuilding with the latest commit in the `master` branch.  (It will take about 1 week.)

**Comment by mourisl** [comment]
The index building from March 1 has some bugs and they are fixed in later commits. Sorry for the trouble.

**Comment by jsh58** [comment]
OK, I was definitely wrong.  With the index built, and the classification done, from the same commit in the `master` branch, there are **no** misassignment issues.

Sorry for the false alarm.  Thanks again for the code changes!
